server:
  port: 4873

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: anonymous-guestbook-service
          uri: lb://ANONYMOUS-GUESTBOOK
          predicates:
            - Path=/api/guestbook/**
          filters:
            - StripPrefix=2
            - SetRequestHeader=Accept, application/json

        - id: account-service
          uri: lb://ACCOUNT
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=1
            - SetRequestHeader=Accept, application/json

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6241/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

